Chore: [AEA-0000] - additional permission now required by AWS (#1966)
## Summary

- :robot: Operational or Infrastructure Change

### Details

Additional permission (ecr:BatchGetImage) now required by AWS to push
image to ECR.

```
unknown: unexpected status from HEAD request to https://591291862413.dkr.ecr.eu-west-2.amazonaws.com/v2/fhir-facade-repo/manifests/sha256:8b2115ad0aa11a93b3bf01db1c15361b9fdfe16f2aa57c928fd6ec14dceebc1f: 403 Forbidden
Error: Process completed with exit code 1.
```

Example of failure:
https://github.com/NHSDigital/electronic-prescription-service-api/actions/runs/21985514803/job/63519879758?pr=4330